### ISSUE TITLE
Testing issue, please ignore it

### ISSUE THREAD

**Issue by Jeffwan** [kitex-contrib/resolver-dns#1]
testing bot

**Comment by ghost** [comment]
@Jeffwan: 
	This request has been marked as needing help from a contributor.

Please ensure the request meets the requirements listed [here](https://git.k8s.io/community/contributors/guide/help-wanted.md).

If this request no longer meets these requirements, the label can be removed
by commenting with the `/remove-help` command.


<details>

In response to [this](https://github.com/kitex-contrib/resolver-dns/issues/1):

>/help


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
